### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by tobyweston** [dgliosca/KiwilandTrains#1]
On a fresh clone (on a Mac), I get the following

    Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

when running
  
    ./gradlew build

Are there files missing from the repo? The wrapper JAR?

**Comment by dgliosca** [comment]
You're right, I accidentally put *.jar into the .gitignore file hence the wrapper didn't land on github. I fixed it
