### ISSUE TITLE
Support old versions of IDEA

### ISSUE THREAD

**Issue by tobyweston** [dgliosca/KiwilandTrains#2]
Impotying on an (embarrassingly) old version of IDEA (2017.2.x) gives me the following

    Error:No such property: GradleVersion for class: JetGradlePlugin

Which is fixed by [downgrading gradle](https://stackoverflow.com/questions/53600179/errorno-such-property-gradleversion-for-class-jetgradleplugin) (apparently).

**Comment by dgliosca** [comment]
I installed IntelliJ 2017.3 and I got any sorts of problems. I did some digging and apparently newer versions of Gradle don't play well with older version of IntelliJ and viceversa. IntelliJ 2017.3 suppports up until Kotlin 1.3.11.

I did some changes to gradle and the code to make it backward compatible with your version of IntelliJ, you may need to manually change the Kotlin plugin version in IntelliJ: 
`Tools -> Kotlin -> Configure Kotlin Plugin Updates` to `1.3.11` 
Please do an update and let me know how it goes.

**Comment by tobyweston** [comment]
Thanks, don't worry too much ;)
